name: Deploy Next App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.x]

    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      VPS_ADDR: ${{ secrets.VPS_ADDR }}  # Set VPS_ADDR as an environment variable

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm i
      - run: npm run build

      - run: mkdir ~/.ssh
      - run: echo "$SSH_KEY" >> ~/.ssh/github-action
      - run: chmod 400 ~/.ssh/github-action

      - run: |
          echo -e "Host vps\n\tUser root\n\tHostname $VPS_ADDR\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config
          

      - run: ssh vps "pm2 stop tongtonginc"
      - run: rsync -re ssh ./.next/ vps:/root/tongtonginc.com-beta/.next
      - run: ssh vps "pm2 start tongtonginc"
